#!/usr/bin/env ruby

require "optparse"
require "optparse/time"
require "futureshop"

SUPPORTED_COMMANDS = %w[orders inventories]

def main(argv)
  global_options = parse_global_options(argv)
  subcommand = argv.shift
  abort "Specify subcommand" unless subcommand
  abort "Unknown subcommand: #{subcommand}" unless SUPPORTED_COMMANDS.include?(subcommand)
  case subcommand
  when "orders"
    orders global_options, argv
  when "inventories"
    inventories global_options, argv
  end
end

def parse_options(argv)
  options = {}
  OptionParser.new {|opt|
    yield opt
  }.order!(argv, into: options)
  options
end

def parse_global_options(argv)
  parse_options(argv) {|opt|
    opt.banner = "Usage:\n" + SUPPORTED_COMMANDS.collect {|command|
      "    #{opt.program_name} [global options] #{command} [options]"
    }.join("\n")
    opt.version = Futureshop::VERSION
    opt.separator "Global options:"
    opt.on "--verbose" do
      $VERBOSE = true
    end
  }
end

def orders(global_options, argv)
  options = {format: "json"}
  options.update(parse_options(argv) {|opt|
    formats = %w[json csv]
    opt.on "-f", "--format=FORMAT", ["json", "csv"], "Output format. Available: #{formats.join(', ')}"
    opt.on "--order-date-start=YYYY-MM-DD", Time, "Retrieve orders whose date is newer than or equal to argument."
    opt.on "--order-date-end=YYYY-MM-DD", Time, "Retrieve orders whose date is older than or equal to argument."
  })
  Futureshop.orders(order_date_start: options[:"order-date-start"], order_date_end: options[:"order-date-end"], format: options[:format])
end

def inventories(global_options, argv)
  require "futureshop/inventory"

  options = {
    type: ["regular"],
    product_no: [],
    jan_code: []
  }
  options = options.update(parse_options(argv) {|opt|
    opt.on "--type=TYPE", Array, "Type. Available: regular, preorder, planned, realstore"
    opt.on "--create-date-start=DATE", Time, "Retrieve products whose registration date is newer than or equal to argument."
    opt.on "--create-date-end=DATE", Time, "Retrieve products whose registration date is older than or equal to argument."
    opt.on "--product-no=NUMBER", Array, "Product number."
    opt.on "--jan-code=CODE", Array, "JAN code."
  })
  if options[:type]
    unknown_types = options[:type].select {|type| ! %w[regular preorder planned realstore].include?(type)}
    unless unknown_types.empty?
      raise "Unknown type(s): #{unknown_types.join(', ')}"
    end
  end
  Futureshop::Inventory.each types: options[:type].collect(&:to_sym), create_date_start: options[:"create-date-start"], create_date_end: options[:"create-date-end"], product_no: options[:"product-no"], jan_code: options[:"jan-code"] do |inventory|
    puts inventory.to_json
  end
end

main ARGV
